stages:
  - build
  - test
  - deploy

variables:
  POSTGRES_DB: klimaathelpdesk
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - ~/.cache/pip/

build_frontend:
  stage: build
  image: node:18-alpine
  script:
    - yarn --frozen-lockfile
    - yarn lint
    - yarn build
  artifacts:
    paths:
      - apps/frontend/static

test:
  stage: test
  image: python:3.10-buster
  needs:
    - build_frontend
  dependencies:
    - build_frontend
  services:
    - postgres:latest
  before_script:
    - python -V
    - pip install --upgrade pip wheel setuptools
    - pip install -r requirements/development.txt
  script:
    - make test ARGS="--ds=settings.gitlab --cov-report term"
  coverage: '/TOTAL.*\s+(\d+%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
    paths:
      - htmlcov/
  interruptible: true

.drone_deploy:
  image: docker-registry.fourdigits.nl/fourdigits-public/docker-pipeline:latest
  stage: deploy
  services:
    - docker:dind
  needs:
    - test
  script:
    - python3 -m fourdigits_cli docker build --push --version=$DEPLOY_VERSION --file=Dockerfile --target=production $DEPLOY_NAME
    - python3 -m fourdigits_cli exonet deploy $DEPLOY_NAME $DEPLOY_VERSION

drone_deploy_tst:
  extends: .drone_deploy
  variables:
    DEPLOY_NAME: tst
    DEPLOY_VERSION: $CI_COMMIT_SHORT_SHA
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  environment:
    name: test
    url: https://klimaathelpdesk.tst.fourdigits.dev

drone_deploy_acc:
  extends: .drone_deploy
  variables:
    DEPLOY_NAME: acc
    DEPLOY_VERSION: $CI_COMMIT_TAG
  rules:
    # Only deploy for semver rc release: X.X.XrcX
    - if: $CI_COMMIT_TAG =~ /.*rc\d+$/
  environment:
    name: acceptation
    url: https://klimaathelpdesk.acc.fourdigits.dev

drone_deploy_prd:
  extends: .drone_deploy
  when: manual
  variables:
    DEPLOY_NAME: prd
    DEPLOY_VERSION: $CI_COMMIT_TAG
  rules:
    # Only deploy on complete semver X.X.X
    - if: $CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+$/
  environment:
    name: production
    url: https://klimaathelpdesk.prd.fourdigits.dev
