services:
  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=klimaathelpdesk
      - POSTGRES_PASSWORD=klimaathelpdesk
      - POSTGRES_DB=klimaathelpdesk
    ports:
         - "5432:5432"
    volumes:
         - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
