# Generated by Django 2.2.9 on 2020-01-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Your Question')),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='User Email')),
                ('date_asked', models.DateTimeField(auto_now_add=True)),
                ('approved', models.NullBooleanField(default=None)),
            ],
        ),
    ]
