# Generated by Django 2.2.9 on 2020-01-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='asked_by_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
