# Generated by Django 3.1.2 on 2020-10-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_footertext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='approved',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
