# Generated by Django 3.1.2 on 2020-11-08 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201024_1519'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FooterText',
        ),
    ]
