# Generated by Django 3.1.2 on 2021-03-07 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_footertext'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.IntegerField(choices=[(0, 'Undecided'), (1, 'Approved'), (2, 'Answered'), (3, 'Rejected')], default=0),
        ),
    ]
