# Generated by Django 3.1.2 on 2021-03-07 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_question_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='categories',
            field=models.TextField(blank=True, null=True, verbose_name='Categories'),
        ),
        migrations.AddField(
            model_name='question',
            name='extra_info',
            field=models.TextField(blank=True, null=True, verbose_name='Extra information'),
        ),
        migrations.AddField(
            model_name='question',
            name='relevant_location',
            field=models.TextField(blank=True, null=True, verbose_name='Relevant location'),
        ),
        migrations.AddField(
            model_name='question',
            name='relevant_timespan',
            field=models.TextField(blank=True, null=True, verbose_name='Relevant timespan'),
        ),
    ]
