# Generated by Django 2.2.9 on 2020-01-12 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_auto_20200112_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='answercategory',
            name='description',
            field=models.CharField(max_length=255, null=True, verbose_name='description'),
        ),
    ]
