# Generated by Django 3.0.5 on 2020-07-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_generalpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='introduction',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
