# Generated by Django 3.0.5 on 2020-08-03 11:27

from django.db import migrations, models
import klimaat_helpdesk.cms.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_generalpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_origin',
            field=wagtail.core.fields.StreamField([('origin', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=255)), ('content', wagtail.core.blocks.RichTextBlock()), ('sources', wagtail.core.blocks.ListBlock(klimaat_helpdesk.cms.blocks.ScientificSourceBlock))]))], default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='introduction',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='page_content',
            field=wagtail.core.fields.StreamField([('richtext', wagtail.core.blocks.StructBlock([('content', wagtail.core.blocks.RichTextBlock())])), ('image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.core.blocks.CharBlock(max_length=250))])), ('quote', wagtail.core.blocks.StructBlock([('quote', wagtail.core.blocks.CharBlock(max_length=1000))]))], default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='related_items',
            field=wagtail.core.fields.StreamField([('related_items', wagtail.core.blocks.StructBlock([('items', wagtail.core.blocks.ListBlock(wagtail.core.blocks.PageChooserBlock(page_type=['cms.Answer'])))]))], default=None),
            preserve_default=False,
        ),
    ]
