# Generated by Django 3.0.5 on 2020-08-03 15:07

from django.db import migrations, models
import klimaat_helpdesk.cms.blocks
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_categoryanswerrelationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='answer',
            name='type',
            field=models.CharField(choices=[('column', 'Column'), ('anwswer', 'Antwoord')], default='answer', max_length=100),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_origin',
            field=wagtail.core.fields.StreamField([('origin', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=255)), ('content', wagtail.core.blocks.RichTextBlock()), ('sources', wagtail.core.blocks.ListBlock(klimaat_helpdesk.cms.blocks.ScientificSourceBlock))]))], blank=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='related_items',
            field=wagtail.core.fields.StreamField([('related_items', wagtail.core.blocks.StructBlock([('items', wagtail.core.blocks.ListBlock(wagtail.core.blocks.PageChooserBlock(page_type=['cms.Answer'])))]))], blank=True),
        ),
    ]
