# Generated by Django 3.0.5 on 2020-07-27 13:31

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_auto_20200727_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='page_content',
            field=wagtail.core.fields.StreamField([('richtext', wagtail.core.blocks.StructBlock([('content', wagtail.core.blocks.RichTextBlock())])), ('image', wagtail.core.blocks.StructBlock([('quote', wagtail.core.blocks.CharBlock(max_length=1000))]))], default=None),
            preserve_default=False,
        ),
    ]
