# Generated by Django 3.0.5 on 2020-08-04 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_auto_20200803_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='type',
            field=models.CharField(choices=[('anwswer', 'Antwoord'), ('column', 'Column')], default='answer', max_length=100),
        ),
    ]
