# Generated by Django 3.0.5 on 2020-08-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_auto_20200804_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='type',
            field=models.CharField(choices=[('answer', 'Antwoord'), ('column', 'Column')], default='answer', max_length=100),
        ),
    ]
