# Generated by Django 3.0.5 on 2020-08-10 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_auto_20200804_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertindexpage',
            name='intro',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AddField(
            model_name='expertindexpage',
            name='outro',
            field=models.TextField(blank=True, max_length=3000),
        ),
    ]
