# Generated by Django 3.0.5 on 2020-08-10 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0015_auto_20200810_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to='cms.AnswerCategory'),
        ),
    ]
