# Generated by Django 3.0.5 on 2020-08-11 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0017_remove_answerindexpage_subtitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='category',
        ),
    ]
