# Generated by Django 3.0.5 on 2020-09-24 12:02

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0018_remove_answer_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='page_content',
            field=wagtail.core.fields.StreamField([('richtext', wagtail.core.blocks.StructBlock([('content', wagtail.core.blocks.RichTextBlock())])), ('image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.core.blocks.CharBlock(max_length=2500))])), ('quote', wagtail.core.blocks.StructBlock([('quote', wagtail.core.blocks.CharBlock(max_length=1000))]))]),
        ),
    ]
