# Generated by Django 3.0.5 on 2020-09-25 07:22

from django.db import migrations
import klimaat_helpdesk.cms.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0019_auto_20200924_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_origin',
            field=wagtail.core.fields.StreamField([('origin', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=255)), ('content', wagtail.core.blocks.RichTextBlock(help_text="Clarification of the answer's origin")), ('sources', wagtail.core.blocks.ListBlock(klimaat_helpdesk.cms.blocks.ScientificSourceBlock))]))], blank=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='content',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='page_content',
            field=wagtail.core.fields.StreamField([('richtext', wagtail.core.blocks.StructBlock([('content', wagtail.core.blocks.RichTextBlock())])), ('image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(help_text='The recommended aspect ratio is landscape with a size of of 1920x1080. Portrait images not recommended.')), ('caption', wagtail.core.blocks.CharBlock(max_length=2500))])), ('quote', wagtail.core.blocks.StructBlock([('quote', wagtail.core.blocks.CharBlock(max_length=1000))]))]),
        ),
    ]
