# Generated by Django 3.1.2 on 2020-11-01 10:22

from django.db import migrations
import klimaat_helpdesk.cms.blocks
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0021_auto_20201101_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_origin',
            field=wagtail.core.fields.StreamField([('origin', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=255)), ('content', wagtail.core.blocks.RichTextBlock(features=('bold', 'italic', 'link', 'document-link'), help_text="Clarification of the answer's origin")), ('sources', wagtail.core.blocks.ListBlock(klimaat_helpdesk.cms.blocks.ScientificSourceBlock))]))], blank=True),
        ),
    ]
