# Generated by Django 3.1.2 on 2020-11-01 10:31

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20201101_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='page_content',
            field=wagtail.core.fields.StreamField([('richtext', wagtail.core.blocks.StructBlock([('content', wagtail.core.blocks.RichTextBlock(features=('h2', 'h3', 'h4', 'image', 'bold', 'italic', 'ol', 'ul', 'hr', 'link', 'document-link', 'embed', 'superscript', 'subscript')))])), ('image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(help_text='The recommended aspect ratio is landscape with a size of of 1920x1080. Portrait images not recommended.')), ('caption', wagtail.core.blocks.CharBlock(max_length=2500))])), ('quote', wagtail.core.blocks.StructBlock([('quote', wagtail.core.blocks.CharBlock(max_length=1000))]))]),
        ),
    ]
