# Generated by Django 3.1.2 on 2020-11-04 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0023_auto_20201101_1031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-first_published_at']},
        ),
    ]
