# Generated by Django 3.1.2 on 2020-11-08 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('cms', '0025_answer_social_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='excerpt',
            field=models.CharField(help_text='This helps with search engines and when sharing on social media', max_length=255, null=True, verbose_name='Short description'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='introduction',
            field=models.TextField(blank=True, default='', help_text='This text is displayed above the tags, useful as a TLDR section', null=True, verbose_name='Introduction'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='social_image',
            field=models.ForeignKey(blank=True, help_text='This is the image that will be displayed when sharing on social media', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='type',
            field=models.CharField(choices=[('answer', 'Antwoord'), ('column', 'Column')], default='answer', help_text='Choose between answer or discussion piece with a more prominent look', max_length=100),
        ),
    ]
