# Generated by Django 3.1.13 on 2021-09-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='affiliation',
            field=models.CharField(blank=True, max_length=128, verbose_name='Affiliation'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='biography'),
        ),
    ]
