# Generated by Django 3.1.13 on 2021-09-19 09:05

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('volunteers', '0002_auto_20210919_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='areas_expertise',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='roles',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='roles'),
        ),
    ]
