# Generated by Django 3.2.16 on 2022-12-21 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GitlabIssue",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("issue_id", models.IntegerField()),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                (
                    "question",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issue",
                        to="core.question",
                    ),
                ),
            ],
        ),
    ]
