# Generated by Django 3.2.16 on 2022-12-21 09:30

from django.db import migrations


def forwards(apps, schema_editor):
    """Import all data from the wagtail_helpdesk GitlabIssues model."""
    OldGitlabIssue = apps.get_model("core", "GitlabIssues")
    GitlabIssue = apps.get_model("gitlab", "GitlabIssue")

    GitlabIssue.objects.bulk_create(
        [
            GitlabIssue(
                question=old.question,
                issue_id=old.issue_id,
                creation_date=old.creation_date,
            )
            for old in OldGitlabIssue.objects.all()
        ]
    )


class Migration(migrations.Migration):

    dependencies = [
        ("gitlab", "0001_initial"),
    ]

    run_before = [
        ("core", "0012_delete_gitlabissues"),
    ]

    operations = [
        migrations.RunPython(forwards),
    ]
