# Generated by Django 3.2.16 on 2022-12-21 09:30

from django.db import migrations

# This migration moved data from the old datamodel (in the wagtail-helpdesk 'core' app)
# into the new one in the 'gitlab' app. Data has been migratied but this migration
# conflicts with changes in the wagtail-helpdesk app, so we made it a noop.


class Migration(migrations.Migration):

    dependencies = [
        ("gitlab", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(migrations.RunPython.noop),
    ]
