# Generated by Django 2.2.9 on 2020-01-11 15:09

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('bio', models.TextField(verbose_name='biography')),
                ('profile_picture', models.FileField(blank=True, upload_to='', verbose_name='Picture')),
                ('affiliation', models.CharField(max_length=128, verbose_name='Affiliation')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('twitter_profile', models.CharField(blank=True, max_length=50, null=True, verbose_name='Twitter Profile')),
                ('linkedin_profile', models.CharField(blank=True, max_length=50, null=True, verbose_name='LinkedIn Profile')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('areas_expertise', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='areas of expertise')),
            ],
        ),
    ]
