# Generated by Django 3.0.5 on 2020-08-04 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0003_expert_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
