# Generated by Django 3.0.5 on 2020-08-11 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('experts', '0004_expert_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='picture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
