# Generated by Django 3.1.2 on 2020-10-24 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0005_auto_20200811_1433'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expert',
            options={'ordering': ['name']},
        ),
    ]
