# Generated by Django 3.2.5 on 2021-07-05 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0007_auto_20201101_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='orcid_profile',
            field=models.URLField(blank=True, null=True, verbose_name='OrcID Link'),
        ),
    ]
